import { FileText, ArrowLeft, ShieldAlert, CheckCircle, Clock } from 'lucide-react';

interface TermsOfServiceProps {
  onBackToHome: () => void;
}

export default function TermsOfService({ onBackToHome }: TermsOfServiceProps) {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 animate-fadeIn" id="terms-of-service-container">
      <button
        onClick={onBackToHome}
        className="group flex items-center gap-2 font-sans text-xs tracking-widest uppercase font-bold text-[#7A7A7A] hover:text-[#2D2D2D] transition-colors mb-10 cursor-pointer min-h-[48px]"
      >
        <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
        Return to Sanctuary Booking
      </button>

      <div className="bg-[#FFFFFF] border border-[#EBEBEB] rounded-3xl p-8 sm:p-12 shadow-[0_4px_24px_rgba(0,0,0,0.02)] text-left">
        <div className="flex items-center gap-3 text-[#A8B5A2] mb-4">
          <FileText className="w-6 h-6" />
          <span className="font-sans text-[10px] tracking-[0.25em] uppercase font-bold">Standard of Sanctuary Agreements</span>
        </div>

        <h1 className="font-serif text-3xl sm:text-4xl font-semibold text-[#2D2D2D] mb-2 leading-tight">
          Terms of Service
        </h1>
        <p className="font-sans text-xs text-[#7A7A7A] italic mb-8">
          Last updated: May 26, 2026
        </p>

        <div className="prose prose-stone max-w-none space-y-8 font-sans text-[#4D4D4D] text-sm leading-relaxed font-light">
          
          <div className="border-b border-[#FAF9F5] pb-6">
            <h2 className="font-serif text-lg font-semibold text-[#2D2D2D] mb-3 flex items-center gap-2">
              <span className="text-[#A8B5A2]">1.</span> Acceptance of Terms
            </h2>
            <p>
              By reserving any high-definition premium cleaning restoration with Aria Clean Service (operating via this web platform), you acknowledge that you have read, understood, and consented to comply with our complete Terms of Service. If you disagree with any segment, please discontinue scheduling bookings.
            </p>
          </div>

          <div className="border-b border-[#FAF9F5] pb-6">
            <h2 className="font-serif text-lg font-semibold text-[#2D2D2D] mb-3 flex items-center gap-2">
              <span className="text-[#A8B5A2]">2.</span> Service Access & Security Protocols
            </h2>
            <p className="mb-3">
              To ensure our professional cleaning specialists can transition into your home seamlessly, clients must agree to:
            </p>
            <ul className="list-disc list-inside pl-4 space-y-2 text-[#7A7A7A]">
              <li>Provide accurate entry coordinates, mechanical keys, active garage clickers, or smart padlock pin codes.</li>
              <li>Provide fully functional electricity, ambient heating/cooling settings, and continuous running water in all target sanitization zones.</li>
              <li>Ensure any heavy decorative installations are securely mounted, and highly valuable antiques, jewelry, or delicate physical ornaments are vaulted before arrival.</li>
            </ul>
          </div>

          <div className="border-b border-[#FAF9F5] pb-6">
            <h2 className="font-serif text-lg font-semibold text-[#2D2D2D] mb-3 flex items-center gap-2">
              <span className="text-[#A8B5A2]">3.</span> Pricing Adjustments & Estimations
            </h2>
            <p>
              All online calculations generated by our standard interactive booking tools are structured as provisional appraisals based on the total dimensions provided. If our clean operations director determines that physical parameters significantly exceed standard specifications, we reserve the right to reassess or audit overall billing with instant, transparent client coordination.
            </p>
          </div>

          <div className="border-b border-[#FAF9F5] pb-6">
            <h2 className="font-serif text-lg font-semibold text-[#2D2D2D] mb-3 flex items-center gap-2">
              <span className="text-[#A8B5A2]">4.</span> Liability, Protection, & Bonding Limits
            </h2>
            <p>
              Aria Clean Service is a premium fully insured, bonded, and vetted organization. While we train our personnel to handle every household asset with delicate precision, our liability for documented accidents is capped at verified material value or standard coverage caps, governed by official insurance parameters.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-lg font-semibold text-[#2D2D2D] mb-3 flex items-center gap-2">
              <span className="text-[#A8B5A2]">5.</span> Dispute Resolution & Governing Jurisdiction
            </h2>
            <p>
              Any operational conflicts, payment details, or service issues are resolved through direct, amicable client-manager email written consultations first. These terms and conditions are strictly regulated in accordance with the state laws where physical operations are executed.
            </p>
          </div>

        </div>

        <div className="mt-12 pt-8 border-t border-[#EBEBEB] flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-xs text-[#7A7A7A]">
            <CheckCircle className="w-4 h-4 text-[#A8B5A2]" />
            <span>Acceptable Conduct Guarantee Protected</span>
          </div>
          <button
            onClick={onBackToHome}
            className="font-sans text-[10px] tracking-[0.2em] uppercase font-bold bg-[#2D2D2D] hover:bg-[#404040] text-white px-6 py-3 rounded-lg transition-colors cursor-pointer"
          >
            Agree & Return
          </button>
        </div>
      </div>
    </div>
  );
}
